import 'package:flutter/material.dart';
import 'package:untitled2/model/word.dart';
import 'package:untitled2/service/local_database.dart';
import 'package:untitled2/utils/actions.dart';
import 'package:untitled2/utils/constants.dart';
import 'package:untitled2/widget/add_word_items.dart';
import 'package:untitled2/widget/buttons.dart';
import 'package:untitled2/widget/common.dart';
import 'package:untitled2/widget/textfield.dart';